### ISSUE TITLE
Middleware needs to be handled better

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-foundation#1]
Currently we have a few issues with middleware as is.

1. Middleware is backend framework specific so at the moment our express generator assumes epxress middleware functions.
2. There is no indication in the middleware about what route type it is being invoked on. This is an issue especially at the resource level middleware because it would be attached to both `Data` and `View` routes and therefore even simple things like issuing a 401 for authentication middleware would not work consistently across the two route types.

For the first one I think we need to introduce a `unthink-foundation` middleware type that is essentially a route handler for middleware vs having the raw middleware from the underlying framework for a few reasons:

- Portability - if we move to KOA or wrap this around AWS lambda/Azure functions the middleware wouldn't have to change.
- It would be consistent for the developer working in this framework for most tasks we are doing in middleware and provides all the same safety the route handlers do. 

Raw middleware for the underlying framework should still be an option but not preferred IMHO. We don't need to lock ourselves out those options because there will be a time where need it for some obscure thing.

In regards to item 2 irrespective of how we handle middleware there are two options that come to mind for this solve:

1. We inject a "type" property into the middleware so that developer can check the type and decide accordingly how to respond per the type. 
    - I feel like this breaks the pattern we have established but for simple middleware could be more compact.
2. We draw a hardline and like routes we have a `view` middleware and `data` middleware. 
   - We do this for routes it would be the most consistent option
   - In some cases the only difference between functions could be a single line choosing `DataResult.error` vs `ViewResult.error`.

I'm leaning toward option two. I think in practice that they will start to diverge enough that having option one would lead to people putting a lot of code to handle both types in one function.

@lxndrdagreat thoughts? I'm going to try to add examples below as a I get time demonstrating the issue and what the solves would look in each approach.

**Comment by tommyphilyaw** [comment]
Here is some code that sketches out the issue with middleware not knowing what the route type. 

```typescript
import { expressResource } from '@epandco/unthink-foundation-express';
import { data, DataResult, view } from '@epandco/unthink-foundation';
import { NextFunction, Request, Response } from 'express';

function getDecodedToken(_req: Request): string {
  // more get decoded token
}

function isTokenValid(_req: Request): boolean {
  // ... validation logic
}

function validateToken(req: Request, res: Response, next: NextFunction ): void {
  if (isTokenValid(req)) {
    // This ONLY works for data routes
    next(DataResult.unauthorized());

    // MUST BE this for view routes
    // next(ViewResult.unauthorized());
  }

  res.locals.token = getDecodedToken(req);
  next();

  return;
}

export default expressResource({
  name: 'Root',
  middleware: [
    validateToken
  ],
  routes: [
    view('/', 'hello-world.njk'),
    data('/message', {
      'get': async (ctx) => DataResult.ok({ value: ctx.path })
    })
  ]
});
```

In this case a single resource has both view and data routes with a single resource level middleware for validating a token. 

When the `data` route is invoked with an invalid token the framework will issue a 401 but when the `view` route is invoked it will return a 500 because internally the `view` error handler doesn't know how to handle the `DataResult`. 

Furthermore there is no sensible choice for the developer here and it's not obvious what its doing. In the current setup the developer would need to create two different middleware functions and install them at the route level for each route.

**Comment by lxndrdagreat** [comment]
> I'm leaning toward option two. I think in practice that they will start to diverge enough that having option one would lead to people putting a lot of code to handle both types in one function.

@tommyphilyaw I'm just not sure that the "diverge enough" is true. One instance I'm thinking of is authentication/claims; the logic for _checking_ auth would be the same, with the only difference being returning a `403` (data) or redirecting to a login page (view). I dislike the idea of having to have `authMiddlewareView` and `authMiddlewareData`. Another example of middleware that "wouldn't care" about route type would be middleware that just sets/consumes query strings, headers or cookies and then stores information on `local`.

Ultimately, I guess what I'm saying is that I don't think option 1 or 2 is a "best" or "most obvious" solution, IMO.

**Comment by tommyphilyaw** [comment]
Yeah I think both options are more or less tradeoffs with no ideal solution but I don't think there are any other solutions to this because ultimately the route type will need to be known to make a robust middleware handler. 

Even middleware you would think shouldn't care about it's type if/when an error occurs it has to know how to react. In fact all middleware should be wrapping the core logic in try/catch to ensure next is called correctly (the reason I want a wrapper around this core middleware in the first part of the issue).

Going beyond handling errors caching middleware may also need to know the type to ensure it renders the the cached content correctly e.g return JSON vs a string / html.

Option 1 was my original thought because I too didn't want two auth functions however here a few things I don't like about that option that cropped up as I was originally writing this:

1. Every middleware would have to check the type even if it's only relevant to one route type. 
2. If you want to for example apply something at the resource level for a `data` route that does not apply to a `view` route you have to explicitly handle this by going if this is a `view` route don't apply the logic and just call next.
3. It starts to feel very polluted with checks even if you don't need them. 

Option 2 avoids those but of you will have two functions in cases where logic is shared between routes. The core logic can of course be abstracted to a function but the route specific stuff would be two functions.

The question is how often would that happen vs route specific middleware. So far beyond authentication the uses I have seen have been specific to a route type which is why I think in practice we may not end up with a lot of cases where we have "two" functions.

**Comment by tommyphilyaw** [comment]
Here are examples of each option in the context of token auth:

Option 1:

```Typescript
function validateToken(req: Request, res: Response, next: NextFunction ): void {
  if (!isTokenValid(req)) {
    // The if block below would have to exist in pretty much all middleware
    // to check type and respond. In this case it's responding with unauthorized but
    // obviously the content in the blocks would change per middleware
    if (res.locals.routeType === UnthinkRouteTypes.DATA) {
      next(DataResult.unauthorized());
    }
    else if (res.locals.routeType === UnthinkRouteTypes.VIEW) {
      next(ViewResult.unauthorized('unauthorized.njk'));
    }
    else {
      next(`validateToken does not support {res.locals.routeType}`);
    }

    return;
  }

  res.locals.token = getDecodedToken(req);
  next();

  return;
}
```

Option 2:

```Typescript
// the validation logic could change so that it sets the res.local.token
// or throw and error return false and then these two functions would literally
// just be either calling next or handling the errror. 

const viewTokenAuth = view((res, req, next) => {
  if (!isTokenValid(req)) {
    next(ViewResult.unauthorized('unauthorized.njk'));
    return;
  }
  
  res.locals.token = getDecodedToken(req);
  next();
});

const dataTokenAuth = data((res, req, next) => {
  if (!isTokenValid(req)) {
    next(DataResult.unauthorized());
    return;
  }

  res.locals.token = getDecodedToken(req);
  next();
});

export default expressResource({
  name: 'Root',
  middleware: [
    viewTokenAuth,
    dataTokenAuth
  ],
  routes: [
    view('/', 'hello-world.njk'),
    data('/message', {
      'get': async (ctx) => DataResult.ok({ value: ctx.path })
    })
  ]
});
```

I need to find some more examples that are route specific and I think it would help highlight issues with either approach.

**Comment by tommyphilyaw** [comment]
34d86842b915027510d67437c0e8ba91eaee7f66 closes this issue
